server {
    listen 80;
    server_name 13.220.133.217; 

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name 13.220.133.217;


    ssl_certificate /etc/letsencrypt/live/13.220.133.217/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/13.220.133.217/privkey.pem;


    location / {
        proxy_pass http://frontend:80; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }


    location /api/ {
        proxy_pass http://backend_api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}