server {
    listen 80;
    server_name handwritter.me www.handwritter.me;

    # Специальный путь для проверки Certbot
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Временно просто прокидываем фронтенд по обычному HTTP
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
    }
}